"""
NSE stock universe, sourced from two authoritative feeds (not hand-recalled):

  - Market-cap tiers + sector/industry: the official Nifty 100 / Nifty Midcap 150 /
    Nifty Smallcap 250 index constituent lists published by NSE Indices Ltd
    (niftyindices.com/IndexConstituent/*.csv) - this is the same methodology SEBI
    requires AMCs to use for large/mid/small-cap classification (rank 1-100 / 101-250 /
    251-500 by full market cap), so "tier" and "industry" below are NSE's own, not a guess.
  - F&O eligibility: derived from Upstox's NSE instrument master
    (assets.upstox.com/market-quote/instruments/exchange/NSE.json.gz), taking the unique
    underlying_symbol of every live NSE_FO equity-derivative contract.

Every symbol here was cross-validated against Upstox's live NSE_EQ instrument list at
generation time (i.e. it was actually a tradeable, correctly-spelled ticker then) - but
both feeds are point-in-time snapshots: NSE reconstitutes these indices semi-annually and
F&O eligibility is reviewed periodically, so this will drift over time. Re-run the same
two-source pull to refresh it; don't hand-edit tier/industry without checking NSE's
current published list.

Symbols are bare (no ".NS"/".BO" suffix) - this project's convention (see
apps/backtests/upstox_client.py) is that a bare symbol defaults to NSE. Upstox's API
takes bare/NSE symbols directly; yfinance needs ".NS" appended, which happens at the
point of use (see apps/screener/tasks.py and static/js/components/universe-picker.js),
not in this data.
"""

# symbol -> {"name": company name, "industry": NSE industry classification, "tier": "large"|"mid"|"small"}
NSE_UNIVERSE = {
    "ABB": {"name": "ABB India Ltd.", "industry": "Capital Goods", "tier": "large"},
    "ADANIENSOL": {"name": "Adani Energy Solutions Ltd.", "industry": "Power", "tier": "large"},
    "ADANIENT": {"name": "Adani Enterprises Ltd.", "industry": "Metals & Mining", "tier": "large"},
    "ADANIGREEN": {"name": "Adani Green Energy Ltd.", "industry": "Power", "tier": "large"},
    "ADANIPORTS": {"name": "Adani Ports and Special Economic Zone Ltd.", "industry": "Services", "tier": "large"},
    "ADANIPOWER": {"name": "Adani Power Ltd.", "industry": "Power", "tier": "large"},
    "AMBUJACEM": {"name": "Ambuja Cements Ltd.", "industry": "Construction Materials", "tier": "large"},
    "APOLLOHOSP": {"name": "Apollo Hospitals Enterprise Ltd.", "industry": "Healthcare", "tier": "large"},
    "ASIANPAINT": {"name": "Asian Paints Ltd.", "industry": "Consumer Durables", "tier": "large"},
    "DMART": {"name": "Avenue Supermarts Ltd.", "industry": "Consumer Services", "tier": "large"},
    "AXISBANK": {"name": "Axis Bank Ltd.", "industry": "Financial Services", "tier": "large"},
    "BAJAJ-AUTO": {"name": "Bajaj Auto Ltd.", "industry": "Automobile and Auto Components", "tier": "large"},
    "BAJFINANCE": {"name": "Bajaj Finance Ltd.", "industry": "Financial Services", "tier": "large"},
    "BAJAJFINSV": {"name": "Bajaj Finserv Ltd.", "industry": "Financial Services", "tier": "large"},
    "BAJAJHLDNG": {"name": "Bajaj Holdings & Investment Ltd.", "industry": "Financial Services", "tier": "large"},
    "BANKBARODA": {"name": "Bank of Baroda", "industry": "Financial Services", "tier": "large"},
    "BEL": {"name": "Bharat Electronics Ltd.", "industry": "Capital Goods", "tier": "large"},
    "BPCL": {"name": "Bharat Petroleum Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "large"},
    "BHARTIARTL": {"name": "Bharti Airtel Ltd.", "industry": "Telecommunication", "tier": "large"},
    "BOSCHLTD": {"name": "Bosch Ltd.", "industry": "Automobile and Auto Components", "tier": "large"},
    "BRITANNIA": {"name": "Britannia Industries Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "large"},
    "CGPOWER": {"name": "CG Power and Industrial Solutions Ltd.", "industry": "Capital Goods", "tier": "large"},
    "CANBK": {"name": "Canara Bank", "industry": "Financial Services", "tier": "large"},
    "CHOLAFIN": {"name": "Cholamandalam Investment and Finance Company Ltd.", "industry": "Financial Services", "tier": "large"},
    "CIPLA": {"name": "Cipla Ltd.", "industry": "Healthcare", "tier": "large"},
    "COALINDIA": {"name": "Coal India Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "large"},
    "CUMMINSIND": {"name": "Cummins India Ltd.", "industry": "Capital Goods", "tier": "large"},
    "DLF": {"name": "DLF Ltd.", "industry": "Realty", "tier": "large"},
    "DIVISLAB": {"name": "Divi's Laboratories Ltd.", "industry": "Healthcare", "tier": "large"},
    "DRREDDY": {"name": "Dr. Reddy's Laboratories Ltd.", "industry": "Healthcare", "tier": "large"},
    "EICHERMOT": {"name": "Eicher Motors Ltd.", "industry": "Automobile and Auto Components", "tier": "large"},
    "ETERNAL": {"name": "Eternal Ltd.", "industry": "Consumer Services", "tier": "large"},
    "GAIL": {"name": "GAIL (India) Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "large"},
    "GODREJCP": {"name": "Godrej Consumer Products Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "large"},
    "GRASIM": {"name": "Grasim Industries Ltd.", "industry": "Construction Materials", "tier": "large"},
    "HCLTECH": {"name": "HCL Technologies Ltd.", "industry": "Information Technology", "tier": "large"},
    "HDFCAMC": {"name": "HDFC Asset Management Company Ltd.", "industry": "Financial Services", "tier": "large"},
    "HDFCBANK": {"name": "HDFC Bank Ltd.", "industry": "Financial Services", "tier": "large"},
    "HDFCLIFE": {"name": "HDFC Life Insurance Company Ltd.", "industry": "Financial Services", "tier": "large"},
    "HINDALCO": {"name": "Hindalco Industries Ltd.", "industry": "Metals & Mining", "tier": "large"},
    "HAL": {"name": "Hindustan Aeronautics Ltd.", "industry": "Capital Goods", "tier": "large"},
    "HINDUNILVR": {"name": "Hindustan Unilever Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "large"},
    "HINDZINC": {"name": "Hindustan Zinc Ltd.", "industry": "Metals & Mining", "tier": "large"},
    "HYUNDAI": {"name": "Hyundai Motor India Ltd.", "industry": "Automobile and Auto Components", "tier": "large"},
    "ICICIBANK": {"name": "ICICI Bank Ltd.", "industry": "Financial Services", "tier": "large"},
    "ITC": {"name": "ITC Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "large"},
    "INDHOTEL": {"name": "Indian Hotels Co. Ltd.", "industry": "Consumer Services", "tier": "large"},
    "IOC": {"name": "Indian Oil Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "large"},
    "IRFC": {"name": "Indian Railway Finance Corporation Ltd.", "industry": "Financial Services", "tier": "large"},
    "INFY": {"name": "Infosys Ltd.", "industry": "Information Technology", "tier": "large"},
    "INDIGO": {"name": "InterGlobe Aviation Ltd.", "industry": "Services", "tier": "large"},
    "JSWSTEEL": {"name": "JSW Steel Ltd.", "industry": "Metals & Mining", "tier": "large"},
    "JINDALSTEL": {"name": "Jindal Steel Ltd.", "industry": "Metals & Mining", "tier": "large"},
    "JIOFIN": {"name": "Jio Financial Services Ltd.", "industry": "Financial Services", "tier": "large"},
    "KOTAKBANK": {"name": "Kotak Mahindra Bank Ltd.", "industry": "Financial Services", "tier": "large"},
    "LTM": {"name": "LTM Ltd.", "industry": "Information Technology", "tier": "large"},
    "LT": {"name": "Larsen & Toubro Ltd.", "industry": "Construction", "tier": "large"},
    "LODHA": {"name": "Lodha Developers Ltd.", "industry": "Realty", "tier": "large"},
    "M&M": {"name": "Mahindra & Mahindra Ltd.", "industry": "Automobile and Auto Components", "tier": "large"},
    "MARUTI": {"name": "Maruti Suzuki India Ltd.", "industry": "Automobile and Auto Components", "tier": "large"},
    "MAXHEALTH": {"name": "Max Healthcare Institute Ltd.", "industry": "Healthcare", "tier": "large"},
    "MAZDOCK": {"name": "Mazagoan Dock Shipbuilders Ltd.", "industry": "Capital Goods", "tier": "large"},
    "MUTHOOTFIN": {"name": "Muthoot Finance Ltd.", "industry": "Financial Services", "tier": "large"},
    "NTPC": {"name": "NTPC Ltd.", "industry": "Power", "tier": "large"},
    "NESTLEIND": {"name": "Nestle India Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "large"},
    "ONGC": {"name": "Oil & Natural Gas Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "large"},
    "PIDILITIND": {"name": "Pidilite Industries Ltd.", "industry": "Chemicals", "tier": "large"},
    "PFC": {"name": "Power Finance Corporation Ltd.", "industry": "Financial Services", "tier": "large"},
    "POWERGRID": {"name": "Power Grid Corporation of India Ltd.", "industry": "Power", "tier": "large"},
    "PNB": {"name": "Punjab National Bank", "industry": "Financial Services", "tier": "large"},
    "RECLTD": {"name": "REC Ltd.", "industry": "Financial Services", "tier": "large"},
    "RELIANCE": {"name": "Reliance Industries Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "large"},
    "SBILIFE": {"name": "SBI Life Insurance Company Ltd.", "industry": "Financial Services", "tier": "large"},
    "MOTHERSON": {"name": "Samvardhana Motherson International Ltd.", "industry": "Automobile and Auto Components", "tier": "large"},
    "SHREECEM": {"name": "Shree Cement Ltd.", "industry": "Construction Materials", "tier": "large"},
    "SHRIRAMFIN": {"name": "Shriram Finance Ltd.", "industry": "Financial Services", "tier": "large"},
    "ENRIN": {"name": "Siemens Energy India Ltd.", "industry": "Capital Goods", "tier": "large"},
    "SIEMENS": {"name": "Siemens Ltd.", "industry": "Capital Goods", "tier": "large"},
    "SOLARINDS": {"name": "Solar Industries India Ltd.", "industry": "Chemicals", "tier": "large"},
    "SBIN": {"name": "State Bank of India", "industry": "Financial Services", "tier": "large"},
    "SUNPHARMA": {"name": "Sun Pharmaceutical Industries Ltd.", "industry": "Healthcare", "tier": "large"},
    "TVSMOTOR": {"name": "TVS Motor Company Ltd.", "industry": "Automobile and Auto Components", "tier": "large"},
    "TATACAP": {"name": "Tata Capital Ltd.", "industry": "Financial Services", "tier": "large"},
    "TCS": {"name": "Tata Consultancy Services Ltd.", "industry": "Information Technology", "tier": "large"},
    "TATACONSUM": {"name": "Tata Consumer Products Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "large"},
    "TMCV": {"name": "Tata Motors Ltd.", "industry": "Capital Goods", "tier": "large"},
    "TMPV": {"name": "Tata Motors Passenger Vehicles Ltd.", "industry": "Automobile and Auto Components", "tier": "large"},
    "TATAPOWER": {"name": "Tata Power Co. Ltd.", "industry": "Power", "tier": "large"},
    "TATASTEEL": {"name": "Tata Steel Ltd.", "industry": "Metals & Mining", "tier": "large"},
    "TECHM": {"name": "Tech Mahindra Ltd.", "industry": "Information Technology", "tier": "large"},
    "TITAN": {"name": "Titan Company Ltd.", "industry": "Consumer Durables", "tier": "large"},
    "TORNTPHARM": {"name": "Torrent Pharmaceuticals Ltd.", "industry": "Healthcare", "tier": "large"},
    "TRENT": {"name": "Trent Ltd.", "industry": "Consumer Services", "tier": "large"},
    "ULTRACEMCO": {"name": "UltraTech Cement Ltd.", "industry": "Construction Materials", "tier": "large"},
    "UNIONBANK": {"name": "Union Bank of India", "industry": "Financial Services", "tier": "large"},
    "UNITDSPR": {"name": "United Spirits Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "large"},
    "VBL": {"name": "Varun Beverages Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "large"},
    "VEDL": {"name": "Vedanta Ltd.", "industry": "Metals & Mining", "tier": "large"},
    "WIPRO": {"name": "Wipro Ltd.", "industry": "Information Technology", "tier": "large"},
    "ZYDUSLIFE": {"name": "Zydus Lifesciences Ltd.", "industry": "Healthcare", "tier": "large"},
    "360ONE": {"name": "360 ONE WAM Ltd.", "industry": "Financial Services", "tier": "mid"},
    "3MINDIA": {"name": "3M India Ltd.", "industry": "Diversified", "tier": "mid"},
    "ACC": {"name": "ACC Ltd.", "industry": "Construction Materials", "tier": "mid"},
    "AIAENG": {"name": "AIA Engineering Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "APLAPOLLO": {"name": "APL Apollo Tubes Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "AUBANK": {"name": "AU Small Finance Bank Ltd.", "industry": "Financial Services", "tier": "mid"},
    "AWL": {"name": "AWL Agri Business Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "mid"},
    "ABBOTINDIA": {"name": "Abbott India Ltd.", "industry": "Healthcare", "tier": "mid"},
    "ATGL": {"name": "Adani Total Gas Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "mid"},
    "ABCAPITAL": {"name": "Aditya Birla Capital Ltd.", "industry": "Financial Services", "tier": "mid"},
    "AJANTPHARM": {"name": "Ajanta Pharmaceuticals Ltd.", "industry": "Healthcare", "tier": "mid"},
    "ALKEM": {"name": "Alkem Laboratories Ltd.", "industry": "Healthcare", "tier": "mid"},
    "ANTHEM": {"name": "Anthem Biosciences Ltd.", "industry": "Healthcare", "tier": "mid"},
    "APARINDS": {"name": "Apar Industries Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "APOLLOTYRE": {"name": "Apollo Tyres Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "ASHOKLEY": {"name": "Ashok Leyland Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "ASTRAL": {"name": "Astral Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "AUROPHARMA": {"name": "Aurobindo Pharma Ltd.", "industry": "Healthcare", "tier": "mid"},
    "AIIL": {"name": "Authum Investment & Infrastructure Ltd.", "industry": "Financial Services", "tier": "mid"},
    "BSE": {"name": "BSE Ltd.", "industry": "Financial Services", "tier": "mid"},
    "BAJAJHFL": {"name": "Bajaj Housing Finance Ltd.", "industry": "Financial Services", "tier": "mid"},
    "BALKRISIND": {"name": "Balkrishna Industries Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "BANKINDIA": {"name": "Bank of India", "industry": "Financial Services", "tier": "mid"},
    "MAHABANK": {"name": "Bank of Maharashtra", "industry": "Financial Services", "tier": "mid"},
    "BERGEPAINT": {"name": "Berger Paints India Ltd.", "industry": "Consumer Durables", "tier": "mid"},
    "BDL": {"name": "Bharat Dynamics Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "BHARATFORG": {"name": "Bharat Forge Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "BHEL": {"name": "Bharat Heavy Electricals Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "BHARTIHEXA": {"name": "Bharti Hexacom Ltd.", "industry": "Telecommunication", "tier": "mid"},
    "GROWW": {"name": "Billionbrains Garage Ventures Ltd.", "industry": "Financial Services", "tier": "mid"},
    "BIOCON": {"name": "Biocon Ltd.", "industry": "Healthcare", "tier": "mid"},
    "BLUESTARCO": {"name": "Blue Star Ltd.", "industry": "Consumer Durables", "tier": "mid"},
    "CRISIL": {"name": "CRISIL Ltd.", "industry": "Financial Services", "tier": "mid"},
    "COCHINSHIP": {"name": "Cochin Shipyard Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "COFORGE": {"name": "Coforge Ltd.", "industry": "Information Technology", "tier": "mid"},
    "COLPAL": {"name": "Colgate Palmolive (India) Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "mid"},
    "CONCOR": {"name": "Container Corporation of India Ltd.", "industry": "Services", "tier": "mid"},
    "COROMANDEL": {"name": "Coromandel International Ltd.", "industry": "Chemicals", "tier": "mid"},
    "DABUR": {"name": "Dabur India Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "mid"},
    "DALBHARAT": {"name": "Dalmia Bharat Ltd.", "industry": "Construction Materials", "tier": "mid"},
    "DIXON": {"name": "Dixon Technologies (India) Ltd.", "industry": "Consumer Durables", "tier": "mid"},
    "ENDURANCE": {"name": "Endurance Technologies Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "ESCORTS": {"name": "Escorts Kubota Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "EXIDEIND": {"name": "Exide Industries Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "NYKAA": {"name": "FSN E-Commerce Ventures Ltd.", "industry": "Consumer Services", "tier": "mid"},
    "FEDERALBNK": {"name": "Federal Bank Ltd.", "industry": "Financial Services", "tier": "mid"},
    "FORTIS": {"name": "Fortis Healthcare Ltd.", "industry": "Healthcare", "tier": "mid"},
    "GVT&D": {"name": "GE Vernova T&D India Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "GMRAIRPORT": {"name": "GMR Airports Ltd.", "industry": "Services", "tier": "mid"},
    "GICRE": {"name": "General Insurance Corporation of India", "industry": "Financial Services", "tier": "mid"},
    "GLAXO": {"name": "Glaxosmithkline Pharmaceuticals Ltd.", "industry": "Healthcare", "tier": "mid"},
    "GLENMARK": {"name": "Glenmark Pharmaceuticals Ltd.", "industry": "Healthcare", "tier": "mid"},
    "MEDANTA": {"name": "Global Health Ltd.", "industry": "Healthcare", "tier": "mid"},
    "GODFRYPHLP": {"name": "Godfrey Phillips India Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "mid"},
    "GODREJIND": {"name": "Godrej Industries Ltd.", "industry": "Diversified", "tier": "mid"},
    "GODREJPROP": {"name": "Godrej Properties Ltd.", "industry": "Realty", "tier": "mid"},
    "FLUOROCHEM": {"name": "Gujarat Fluorochemicals Ltd.", "industry": "Chemicals", "tier": "mid"},
    "HDBFS": {"name": "HDB Financial Services Ltd.", "industry": "Financial Services", "tier": "mid"},
    "HAVELLS": {"name": "Havells India Ltd.", "industry": "Consumer Durables", "tier": "mid"},
    "HEROMOTOCO": {"name": "Hero MotoCorp Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "HEXT": {"name": "Hexaware Technologies Ltd.", "industry": "Information Technology", "tier": "mid"},
    "HINDPETRO": {"name": "Hindustan Petroleum Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "mid"},
    "POWERINDIA": {"name": "Hitachi Energy India Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "HONAUT": {"name": "Honeywell Automation India Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "HUDCO": {"name": "Housing & Urban Development Corporation Ltd.", "industry": "Financial Services", "tier": "mid"},
    "ICICIGI": {"name": "ICICI Lombard General Insurance Company Ltd.", "industry": "Financial Services", "tier": "mid"},
    "ICICIAMC": {"name": "ICICI Prudential Asset Management Company Ltd.", "industry": "Financial Services", "tier": "mid"},
    "ICICIPRULI": {"name": "ICICI Prudential Life Insurance Company Ltd.", "industry": "Financial Services", "tier": "mid"},
    "IDFCFIRSTB": {"name": "IDFC First Bank Ltd.", "industry": "Financial Services", "tier": "mid"},
    "ITCHOTELS": {"name": "ITC Hotels Ltd.", "industry": "Consumer Services", "tier": "mid"},
    "INDIANB": {"name": "Indian Bank", "industry": "Financial Services", "tier": "mid"},
    "IRCTC": {"name": "Indian Railway Catering And Tourism Corporation Ltd.", "industry": "Consumer Services", "tier": "mid"},
    "IREDA": {"name": "Indian Renewable Energy Development Agency Ltd.", "industry": "Financial Services", "tier": "mid"},
    "INDUSTOWER": {"name": "Indus Towers Ltd.", "industry": "Telecommunication", "tier": "mid"},
    "INDUSINDBK": {"name": "IndusInd Bank Ltd.", "industry": "Financial Services", "tier": "mid"},
    "NAUKRI": {"name": "Info Edge (India) Ltd.", "industry": "Consumer Services", "tier": "mid"},
    "IPCALAB": {"name": "Ipca Laboratories Ltd.", "industry": "Healthcare", "tier": "mid"},
    "JKCEMENT": {"name": "J.K. Cement Ltd.", "industry": "Construction Materials", "tier": "mid"},
    "JSWENERGY": {"name": "JSW Energy Ltd.", "industry": "Power", "tier": "mid"},
    "JSWINFRA": {"name": "JSW Infrastructure Ltd.", "industry": "Services", "tier": "mid"},
    "JSL": {"name": "Jindal Stainless Ltd.", "industry": "Metals & Mining", "tier": "mid"},
    "JUBLFOOD": {"name": "Jubilant Foodworks Ltd.", "industry": "Consumer Services", "tier": "mid"},
    "KPRMILL": {"name": "K.P.R. Mill Ltd.", "industry": "Textiles", "tier": "mid"},
    "KEI": {"name": "KEI Industries Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "KPITTECH": {"name": "KPIT Technologies Ltd.", "industry": "Information Technology", "tier": "mid"},
    "KALYANKJIL": {"name": "Kalyan Jewellers India Ltd.", "industry": "Consumer Durables", "tier": "mid"},
    "LTF": {"name": "L&T Finance Ltd.", "industry": "Financial Services", "tier": "mid"},
    "LTTS": {"name": "L&T Technology Services Ltd.", "industry": "Information Technology", "tier": "mid"},
    "LGEINDIA": {"name": "LG Electronics India Ltd.", "industry": "Consumer Durables", "tier": "mid"},
    "LICHSGFIN": {"name": "LIC Housing Finance Ltd.", "industry": "Financial Services", "tier": "mid"},
    "LAURUSLABS": {"name": "Laurus Labs Ltd.", "industry": "Healthcare", "tier": "mid"},
    "LENSKART": {"name": "Lenskart Solutions Ltd.", "industry": "Consumer Services", "tier": "mid"},
    "LICI": {"name": "Life Insurance Corporation of India", "industry": "Financial Services", "tier": "mid"},
    "LINDEINDIA": {"name": "Linde India Ltd.", "industry": "Chemicals", "tier": "mid"},
    "LLOYDSME": {"name": "Lloyds Metals And Energy Ltd.", "industry": "Metals & Mining", "tier": "mid"},
    "LUPIN": {"name": "Lupin Ltd.", "industry": "Healthcare", "tier": "mid"},
    "MRF": {"name": "MRF Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "M&MFIN": {"name": "Mahindra & Mahindra Financial Services Ltd.", "industry": "Financial Services", "tier": "mid"},
    "MANKIND": {"name": "Mankind Pharma Ltd.", "industry": "Healthcare", "tier": "mid"},
    "MARICO": {"name": "Marico Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "mid"},
    "MFSL": {"name": "Max Financial Services Ltd.", "industry": "Financial Services", "tier": "mid"},
    "MOTILALOFS": {"name": "Motilal Oswal Financial Services Ltd.", "industry": "Financial Services", "tier": "mid"},
    "MPHASIS": {"name": "MphasiS Ltd.", "industry": "Information Technology", "tier": "mid"},
    "MCX": {"name": "Multi Commodity Exchange of India Ltd.", "industry": "Financial Services", "tier": "mid"},
    "NHPC": {"name": "NHPC Ltd.", "industry": "Power", "tier": "mid"},
    "NLCINDIA": {"name": "NLC India Ltd.", "industry": "Power", "tier": "mid"},
    "NMDC": {"name": "NMDC Ltd.", "industry": "Metals & Mining", "tier": "mid"},
    "NTPCGREEN": {"name": "NTPC Green Energy Ltd.", "industry": "Power", "tier": "mid"},
    "NATIONALUM": {"name": "National Aluminium Co. Ltd.", "industry": "Metals & Mining", "tier": "mid"},
    "NAM-INDIA": {"name": "Nippon Life India Asset Management Ltd.", "industry": "Financial Services", "tier": "mid"},
    "OBEROIRLTY": {"name": "Oberoi Realty Ltd.", "industry": "Realty", "tier": "mid"},
    "OIL": {"name": "Oil India Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "mid"},
    "PAYTM": {"name": "One 97 Communications Ltd.", "industry": "Financial Services", "tier": "mid"},
    "OFSS": {"name": "Oracle Financial Services Software Ltd.", "industry": "Information Technology", "tier": "mid"},
    "POLICYBZR": {"name": "PB Fintech Ltd.", "industry": "Financial Services", "tier": "mid"},
    "PIIND": {"name": "PI Industries Ltd.", "industry": "Chemicals", "tier": "mid"},
    "PAGEIND": {"name": "Page Industries Ltd.", "industry": "Textiles", "tier": "mid"},
    "PATANJALI": {"name": "Patanjali Foods Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "mid"},
    "PERSISTENT": {"name": "Persistent Systems Ltd.", "industry": "Information Technology", "tier": "mid"},
    "PETRONET": {"name": "Petronet LNG Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "mid"},
    "PHOENIXLTD": {"name": "Phoenix Mills Ltd.", "industry": "Realty", "tier": "mid"},
    "POLYCAB": {"name": "Polycab India Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "PREMIERENE": {"name": "Premier Energies Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "PRESTIGE": {"name": "Prestige Estates Projects Ltd.", "industry": "Realty", "tier": "mid"},
    "RADICO": {"name": "Radico Khaitan Ltd", "industry": "Fast Moving Consumer Goods", "tier": "mid"},
    "RVNL": {"name": "Rail Vikas Nigam Ltd.", "industry": "Construction", "tier": "mid"},
    "SBICARD": {"name": "SBI Cards and Payment Services Ltd.", "industry": "Financial Services", "tier": "mid"},
    "SJVN": {"name": "SJVN Ltd.", "industry": "Power", "tier": "mid"},
    "SRF": {"name": "SRF Ltd.", "industry": "Chemicals", "tier": "mid"},
    "SCHAEFFLER": {"name": "Schaeffler India Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "SAIL": {"name": "Steel Authority of India Ltd.", "industry": "Metals & Mining", "tier": "mid"},
    "SUNDARMFIN": {"name": "Sundaram Finance Ltd.", "industry": "Financial Services", "tier": "mid"},
    "SUPREMEIND": {"name": "Supreme Industries Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "SUZLON": {"name": "Suzlon Energy Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "SWIGGY": {"name": "Swiggy Ltd.", "industry": "Consumer Services", "tier": "mid"},
    "TATACOMM": {"name": "Tata Communications Ltd.", "industry": "Telecommunication", "tier": "mid"},
    "TATAELXSI": {"name": "Tata Elxsi Ltd.", "industry": "Information Technology", "tier": "mid"},
    "TATAINVEST": {"name": "Tata Investment Corporation Ltd.", "industry": "Financial Services", "tier": "mid"},
    "NIACL": {"name": "The New India Assurance Company Ltd.", "industry": "Financial Services", "tier": "mid"},
    "THERMAX": {"name": "Thermax Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "TORNTPOWER": {"name": "Torrent Power Ltd.", "industry": "Power", "tier": "mid"},
    "TIINDIA": {"name": "Tube Investments of India Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "UNOMINDA": {"name": "UNO Minda Ltd.", "industry": "Automobile and Auto Components", "tier": "mid"},
    "UPL": {"name": "UPL Ltd.", "industry": "Chemicals", "tier": "mid"},
    "UBL": {"name": "United Breweries Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "mid"},
    "VMM": {"name": "Vishal Mega Mart Ltd.", "industry": "Consumer Services", "tier": "mid"},
    "IDEA": {"name": "Vodafone Idea Ltd.", "industry": "Telecommunication", "tier": "mid"},
    "VOLTAS": {"name": "Voltas Ltd.", "industry": "Consumer Durables", "tier": "mid"},
    "WAAREEENER": {"name": "Waaree Energies Ltd.", "industry": "Capital Goods", "tier": "mid"},
    "YESBANK": {"name": "Yes Bank Ltd.", "industry": "Financial Services", "tier": "mid"},
    "ACMESOLAR": {"name": "ACME Solar Holdings Ltd.", "industry": "Power", "tier": "small"},
    "AADHARHFC": {"name": "Aadhar Housing Finance Ltd.", "industry": "Financial Services", "tier": "small"},
    "AARTIIND": {"name": "Aarti Industries Ltd.", "industry": "Chemicals", "tier": "small"},
    "AAVAS": {"name": "Aavas Financiers Ltd.", "industry": "Financial Services", "tier": "small"},
    "ACE": {"name": "Action Construction Equipment Ltd.", "industry": "Capital Goods", "tier": "small"},
    "ACUTAAS": {"name": "Acutaas Chemicals Ltd.", "industry": "Healthcare", "tier": "small"},
    "ABLBL": {"name": "Aditya Birla Lifestyle Brands Ltd.", "industry": "Consumer Services", "tier": "small"},
    "ABREL": {"name": "Aditya Birla Real Estate Ltd.", "industry": "Realty", "tier": "small"},
    "ABSLAMC": {"name": "Aditya Birla Sun Life AMC Ltd.", "industry": "Financial Services", "tier": "small"},
    "CPPLUS": {"name": "Aditya Infotech Ltd.", "industry": "Capital Goods", "tier": "small"},
    "AEGISLOG": {"name": "Aegis Logistics Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "small"},
    "AEGISVOPAK": {"name": "Aegis Vopak Terminals Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "small"},
    "AFCONS": {"name": "Afcons Infrastructure Ltd.", "industry": "Construction", "tier": "small"},
    "AFFLE": {"name": "Affle 3i Ltd.", "industry": "Information Technology", "tier": "small"},
    "ABDL": {"name": "Allied Blenders and Distillers Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "ARE&M": {"name": "Amara Raja Energy & Mobility Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "AMBER": {"name": "Amber Enterprises India Ltd.", "industry": "Consumer Durables", "tier": "small"},
    "ANANDRATHI": {"name": "Anand Rathi Wealth Ltd.", "industry": "Financial Services", "tier": "small"},
    "ANANTRAJ": {"name": "Anant Raj Ltd.", "industry": "Realty", "tier": "small"},
    "ANGELONE": {"name": "Angel One Ltd.", "industry": "Financial Services", "tier": "small"},
    "ANURAS": {"name": "Anupam Rasayan India Ltd.", "industry": "Chemicals", "tier": "small"},
    "APTUS": {"name": "Aptus Value Housing Finance India Ltd.", "industry": "Financial Services", "tier": "small"},
    "ASAHIINDIA": {"name": "Asahi India Glass Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "ASTERDM": {"name": "Aster DM Healthcare Ltd.", "industry": "Healthcare", "tier": "small"},
    "ATHERENERG": {"name": "Ather Energy Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "ATUL": {"name": "Atul Ltd.", "industry": "Chemicals", "tier": "small"},
    "BEML": {"name": "BEML Ltd.", "industry": "Capital Goods", "tier": "small"},
    "BLS": {"name": "BLS International Services Ltd.", "industry": "Consumer Services", "tier": "small"},
    "BALRAMCHIN": {"name": "Balrampur Chini Mills Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "BANDHANBNK": {"name": "Bandhan Bank Ltd.", "industry": "Financial Services", "tier": "small"},
    "BATAINDIA": {"name": "Bata India Ltd.", "industry": "Consumer Durables", "tier": "small"},
    "BAYERCROP": {"name": "Bayer Cropscience Ltd.", "industry": "Chemicals", "tier": "small"},
    "BELRISE": {"name": "Belrise Industries Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "BIKAJI": {"name": "Bikaji Foods International Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "BSOFT": {"name": "Birlasoft Ltd.", "industry": "Information Technology", "tier": "small"},
    "BLUEDART": {"name": "Blue Dart Express Ltd.", "industry": "Services", "tier": "small"},
    "BLUEJET": {"name": "Blue Jet Healthcare Ltd.", "industry": "Healthcare", "tier": "small"},
    "BBTC": {"name": "Bombay Burmah Trading Corporation Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "FIRSTCRY": {"name": "Brainbees Solutions Ltd.", "industry": "Consumer Services", "tier": "small"},
    "BRIGADE": {"name": "Brigade Enterprises Ltd.", "industry": "Realty", "tier": "small"},
    "MAPMYINDIA": {"name": "C.E. Info Systems Ltd.", "industry": "Information Technology", "tier": "small"},
    "CCL": {"name": "CCL Products (I) Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "CESC": {"name": "CESC Ltd.", "industry": "Power", "tier": "small"},
    "CIEINDIA": {"name": "CIE Automotive India Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "CANFINHOME": {"name": "Can Fin Homes Ltd.", "industry": "Financial Services", "tier": "small"},
    "CANHLIFE": {"name": "Canara HSBC Life Insurance Company Ltd.", "industry": "Financial Services", "tier": "small"},
    "CAPLIPOINT": {"name": "Caplin Point Laboratories Ltd.", "industry": "Healthcare", "tier": "small"},
    "CGCL": {"name": "Capri Global Capital Ltd.", "industry": "Financial Services", "tier": "small"},
    "CARBORUNIV": {"name": "Carborundum Universal Ltd.", "industry": "Capital Goods", "tier": "small"},
    "CARTRADE": {"name": "Cartrade Tech Ltd.", "industry": "Consumer Services", "tier": "small"},
    "CASTROLIND": {"name": "Castrol India Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "small"},
    "CEATLTD": {"name": "Ceat Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "CEMPRO": {"name": "Cemindia Projects Ltd.", "industry": "Construction", "tier": "small"},
    "CENTRALBK": {"name": "Central Bank of India", "industry": "Financial Services", "tier": "small"},
    "CDSL": {"name": "Central Depository Services (India) Ltd.", "industry": "Financial Services", "tier": "small"},
    "CHALET": {"name": "Chalet Hotels Ltd.", "industry": "Consumer Services", "tier": "small"},
    "CHAMBLFERT": {"name": "Chambal Fertilizers & Chemicals Ltd.", "industry": "Chemicals", "tier": "small"},
    "CHENNPETRO": {"name": "Chennai Petroleum Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "small"},
    "CHOICEIN": {"name": "Choice International Ltd.", "industry": "Financial Services", "tier": "small"},
    "CHOLAHLDNG": {"name": "Cholamandalam Financial Holdings Ltd.", "industry": "Financial Services", "tier": "small"},
    "CUB": {"name": "City Union Bank Ltd.", "industry": "Financial Services", "tier": "small"},
    "CLEAN": {"name": "Clean Science and Technology Ltd.", "industry": "Chemicals", "tier": "small"},
    "COHANCE": {"name": "Cohance Lifesciences Ltd.", "industry": "Healthcare", "tier": "small"},
    "CAMS": {"name": "Computer Age Management Services Ltd.", "industry": "Financial Services", "tier": "small"},
    "CONCORDBIO": {"name": "Concord Biotech Ltd.", "industry": "Healthcare", "tier": "small"},
    "CRAFTSMAN": {"name": "Craftsman Automation Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "CREDITACC": {"name": "CreditAccess Grameen Ltd.", "industry": "Financial Services", "tier": "small"},
    "CROMPTON": {"name": "Crompton Greaves Consumer Electricals Ltd.", "industry": "Consumer Durables", "tier": "small"},
    "CYIENT": {"name": "Cyient Ltd.", "industry": "Information Technology", "tier": "small"},
    "DCMSHRIRAM": {"name": "DCM Shriram Ltd.", "industry": "Diversified", "tier": "small"},
    "DOMS": {"name": "DOMS Industries Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "DATAPATTNS": {"name": "Data Patterns (India) Ltd.", "industry": "Capital Goods", "tier": "small"},
    "DEEPAKFERT": {"name": "Deepak Fertilisers & Petrochemicals Corp. Ltd.", "industry": "Chemicals", "tier": "small"},
    "DEEPAKNTR": {"name": "Deepak Nitrite Ltd.", "industry": "Chemicals", "tier": "small"},
    "DELHIVERY": {"name": "Delhivery Ltd.", "industry": "Services", "tier": "small"},
    "DEVYANI": {"name": "Devyani International Ltd.", "industry": "Consumer Services", "tier": "small"},
    "LALPATHLAB": {"name": "Dr. Lal Path Labs Ltd.", "industry": "Healthcare", "tier": "small"},
    "EIDPARRY": {"name": "E.I.D. Parry (India) Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "EIHOTEL": {"name": "EIH Ltd.", "industry": "Consumer Services", "tier": "small"},
    "ELECON": {"name": "Elecon Engineering Co. Ltd.", "industry": "Capital Goods", "tier": "small"},
    "ELGIEQUIP": {"name": "Elgi Equipments Ltd.", "industry": "Capital Goods", "tier": "small"},
    "EMAMILTD": {"name": "Emami Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "EMCURE": {"name": "Emcure Pharmaceuticals Ltd.", "industry": "Healthcare", "tier": "small"},
    "EMMVEE": {"name": "Emmvee Photovoltaic Power Ltd.", "industry": "Capital Goods", "tier": "small"},
    "ENGINERSIN": {"name": "Engineers India Ltd.", "industry": "Construction", "tier": "small"},
    "ERIS": {"name": "Eris Lifesciences Ltd.", "industry": "Healthcare", "tier": "small"},
    "FACT": {"name": "Fertilisers and Chemicals Travancore Ltd.", "industry": "Chemicals", "tier": "small"},
    "FINCABLES": {"name": "Finolex Cables Ltd.", "industry": "Capital Goods", "tier": "small"},
    "FSL": {"name": "Firstsource Solutions Ltd.", "industry": "Services", "tier": "small"},
    "FIVESTAR": {"name": "Five-Star Business Finance Ltd.", "industry": "Financial Services", "tier": "small"},
    "FORCEMOT": {"name": "Force Motors Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "GABRIEL": {"name": "Gabriel India Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "GALLANTT": {"name": "Gallantt Ispat Ltd.", "industry": "Capital Goods", "tier": "small"},
    "GRSE": {"name": "Garden Reach Shipbuilders & Engineers Ltd.", "industry": "Capital Goods", "tier": "small"},
    "GILLETTE": {"name": "Gillette India Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "GLAND": {"name": "Gland Pharma Ltd.", "industry": "Healthcare", "tier": "small"},
    "GODIGIT": {"name": "Go Digit General Insurance Ltd.", "industry": "Financial Services", "tier": "small"},
    "GPIL": {"name": "Godawari Power & Ispat Ltd.", "industry": "Capital Goods", "tier": "small"},
    "GRANULES": {"name": "Granules India Ltd.", "industry": "Healthcare", "tier": "small"},
    "GRAPHITE": {"name": "Graphite India Ltd.", "industry": "Capital Goods", "tier": "small"},
    "GRAVITA": {"name": "Gravita India Ltd.", "industry": "Metals & Mining", "tier": "small"},
    "GESHIP": {"name": "Great Eastern Shipping Co. Ltd.", "industry": "Services", "tier": "small"},
    "GMDCLTD": {"name": "Gujarat Mineral Development Corporation Ltd.", "industry": "Metals & Mining", "tier": "small"},
    "HEG": {"name": "H.E.G. Ltd.", "industry": "Capital Goods", "tier": "small"},
    "HBLENGINE": {"name": "HBL Engineering Ltd.", "industry": "Capital Goods", "tier": "small"},
    "HFCL": {"name": "HFCL Ltd.", "industry": "Telecommunication", "tier": "small"},
    "HSCL": {"name": "Himadri Speciality Chemical Ltd.", "industry": "Chemicals", "tier": "small"},
    "HINDCOPPER": {"name": "Hindustan Copper Ltd.", "industry": "Metals & Mining", "tier": "small"},
    "HOMEFIRST": {"name": "Home First Finance Company India Ltd.", "industry": "Financial Services", "tier": "small"},
    "HONASA": {"name": "Honasa Consumer Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "IDBI": {"name": "IDBI Bank Ltd.", "industry": "Financial Services", "tier": "small"},
    "IFCI": {"name": "IFCI Ltd.", "industry": "Financial Services", "tier": "small"},
    "IIFL": {"name": "IIFL Finance Ltd.", "industry": "Financial Services", "tier": "small"},
    "IRB": {"name": "IRB Infrastructure Developers Ltd.", "industry": "Construction", "tier": "small"},
    "IRCON": {"name": "IRCON International Ltd.", "industry": "Construction", "tier": "small"},
    "ITI": {"name": "ITI Ltd.", "industry": "Telecommunication", "tier": "small"},
    "INDGN": {"name": "Indegene Ltd.", "industry": "Healthcare", "tier": "small"},
    "INDIACEM": {"name": "India Cements Ltd.", "industry": "Construction Materials", "tier": "small"},
    "INDIAMART": {"name": "Indiamart Intermesh Ltd.", "industry": "Consumer Services", "tier": "small"},
    "IEX": {"name": "Indian Energy Exchange Ltd.", "industry": "Financial Services", "tier": "small"},
    "IOB": {"name": "Indian Overseas Bank", "industry": "Financial Services", "tier": "small"},
    "IGL": {"name": "Indraprastha Gas Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "small"},
    "INOXWIND": {"name": "Inox Wind Ltd.", "industry": "Capital Goods", "tier": "small"},
    "INTELLECT": {"name": "Intellect Design Arena Ltd.", "industry": "Information Technology", "tier": "small"},
    "IGIL": {"name": "International Gemological Institute Ltd.", "industry": "Services", "tier": "small"},
    "IKS": {"name": "Inventurus Knowledge Solutions Ltd.", "industry": "Information Technology", "tier": "small"},
    "JBMA": {"name": "JBM Auto Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "JKTYRE": {"name": "JK Tyre & Industries Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "JMFINANCIL": {"name": "JM Financial Ltd.", "industry": "Financial Services", "tier": "small"},
    "JSWCEMENT": {"name": "JSW Cement Ltd.", "industry": "Construction Materials", "tier": "small"},
    "JSWDULUX": {"name": "JSW Dulux Ltd.", "industry": "Consumer Durables", "tier": "small"},
    "JAINREC": {"name": "Jain Resource Recycling Ltd.", "industry": "Metals & Mining", "tier": "small"},
    "JPPOWER": {"name": "Jaiprakash Power Ventures Ltd.", "industry": "Power", "tier": "small"},
    "J&KBANK": {"name": "Jammu & Kashmir Bank Ltd.", "industry": "Financial Services", "tier": "small"},
    "JINDALSAW": {"name": "Jindal Saw Ltd.", "industry": "Capital Goods", "tier": "small"},
    "JUBLINGREA": {"name": "Jubilant Ingrevia Ltd.", "industry": "Chemicals", "tier": "small"},
    "JUBLPHARMA": {"name": "Jubilant Pharmova Ltd.", "industry": "Healthcare", "tier": "small"},
    "JWL": {"name": "Jupiter Wagons Ltd.", "industry": "Capital Goods", "tier": "small"},
    "JYOTICNC": {"name": "Jyoti CNC Automation Ltd.", "industry": "Capital Goods", "tier": "small"},
    "KAJARIACER": {"name": "Kajaria Ceramics Ltd.", "industry": "Consumer Durables", "tier": "small"},
    "KPIL": {"name": "Kalpataru Projects International Ltd.", "industry": "Construction", "tier": "small"},
    "KARURVYSYA": {"name": "Karur Vysya Bank Ltd.", "industry": "Financial Services", "tier": "small"},
    "KAYNES": {"name": "Kaynes Technology India Ltd.", "industry": "Capital Goods", "tier": "small"},
    "KEC": {"name": "Kec International Ltd.", "industry": "Construction", "tier": "small"},
    "KFINTECH": {"name": "Kfin Technologies Ltd.", "industry": "Financial Services", "tier": "small"},
    "KIRLOSENG": {"name": "Kirloskar Oil Eng Ltd.", "industry": "Capital Goods", "tier": "small"},
    "KIMS": {"name": "Krishna Institute of Medical Sciences Ltd.", "industry": "Healthcare", "tier": "small"},
    "LTFOODS": {"name": "LT Foods Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "LATENTVIEW": {"name": "Latent View Analytics Ltd.", "industry": "Information Technology", "tier": "small"},
    "THELEELA": {"name": "Leela Palaces Hotels & Resorts Ltd.", "industry": "Consumer Services", "tier": "small"},
    "LEMONTREE": {"name": "Lemon Tree Hotels Ltd.", "industry": "Consumer Services", "tier": "small"},
    "MMTC": {"name": "MMTC Ltd.", "industry": "Services", "tier": "small"},
    "MGL": {"name": "Mahanagar Gas Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "small"},
    "MANAPPURAM": {"name": "Manappuram Finance Ltd.", "industry": "Financial Services", "tier": "small"},
    "MRPL": {"name": "Mangalore Refinery & Petrochemicals Ltd.", "industry": "Oil Gas & Consumable Fuels", "tier": "small"},
    "MEESHO": {"name": "Meesho Ltd.", "industry": "Consumer Services", "tier": "small"},
    "MINDACORP": {"name": "Minda Corporation Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "MSUMI": {"name": "Motherson Sumi Wiring India Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "NATCOPHARM": {"name": "NATCO Pharma Ltd.", "industry": "Healthcare", "tier": "small"},
    "NBCC": {"name": "NBCC (India) Ltd.", "industry": "Construction", "tier": "small"},
    "NCC": {"name": "NCC Ltd.", "industry": "Construction", "tier": "small"},
    "NSLNISP": {"name": "NMDC Steel Ltd.", "industry": "Metals & Mining", "tier": "small"},
    "NH": {"name": "Narayana Hrudayalaya Ltd.", "industry": "Healthcare", "tier": "small"},
    "NAVA": {"name": "Nava Ltd.", "industry": "Power", "tier": "small"},
    "NAVINFLUOR": {"name": "Navin Fluorine International Ltd.", "industry": "Chemicals", "tier": "small"},
    "NETWEB": {"name": "Netweb Technologies India Ltd.", "industry": "Information Technology", "tier": "small"},
    "NEULANDLAB": {"name": "Neuland Laboratories Ltd.", "industry": "Healthcare", "tier": "small"},
    "NEWGEN": {"name": "Newgen Software Technologies Ltd.", "industry": "Information Technology", "tier": "small"},
    "NIVABUPA": {"name": "Niva Bupa Health Insurance Company Ltd.", "industry": "Financial Services", "tier": "small"},
    "NUVAMA": {"name": "Nuvama Wealth Management Ltd.", "industry": "Financial Services", "tier": "small"},
    "NUVOCO": {"name": "Nuvoco Vistas Corporation Ltd.", "industry": "Construction Materials", "tier": "small"},
    "OLAELEC": {"name": "Ola Electric Mobility Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "OLECTRA": {"name": "Olectra Greentech Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "ONESOURCE": {"name": "Onesource Specialty Pharma Ltd.", "industry": "Healthcare", "tier": "small"},
    "PCBL": {"name": "PCBL Chemical Ltd.", "industry": "Chemicals", "tier": "small"},
    "PGEL": {"name": "PG Electroplast Ltd.", "industry": "Consumer Durables", "tier": "small"},
    "PNBHOUSING": {"name": "PNB Housing Finance Ltd.", "industry": "Financial Services", "tier": "small"},
    "PTCIL": {"name": "PTC Industries Ltd.", "industry": "Capital Goods", "tier": "small"},
    "PVRINOX": {"name": "PVR INOX Ltd.", "industry": "Media Entertainment & Publication", "tier": "small"},
    "PARADEEP": {"name": "Paradeep Phosphates Ltd.", "industry": "Chemicals", "tier": "small"},
    "PFIZER": {"name": "Pfizer Ltd.", "industry": "Healthcare", "tier": "small"},
    "PWL": {"name": "Physicswallah Ltd.", "industry": "Consumer Services", "tier": "small"},
    "PINELABS": {"name": "Pine Labs Ltd.", "industry": "Financial Services", "tier": "small"},
    "PIRAMALFIN": {"name": "Piramal Finance Ltd.", "industry": "Financial Services", "tier": "small"},
    "PPLPHARMA": {"name": "Piramal Pharma Ltd.", "industry": "Healthcare", "tier": "small"},
    "POLYMED": {"name": "Poly Medicure Ltd.", "industry": "Healthcare", "tier": "small"},
    "POONAWALLA": {"name": "Poonawalla Fincorp Ltd.", "industry": "Financial Services", "tier": "small"},
    "PFOCUS": {"name": "Prime Focus Ltd.", "industry": "Media Entertainment & Publication", "tier": "small"},
    "RRKABEL": {"name": "R R Kabel Ltd.", "industry": "Capital Goods", "tier": "small"},
    "RBLBANK": {"name": "RBL Bank Ltd.", "industry": "Financial Services", "tier": "small"},
    "RHIM": {"name": "RHI MAGNESITA INDIA LTD.", "industry": "Capital Goods", "tier": "small"},
    "RITES": {"name": "RITES Ltd.", "industry": "Construction", "tier": "small"},
    "RAILTEL": {"name": "Railtel Corporation Of India Ltd.", "industry": "Telecommunication", "tier": "small"},
    "RAINBOW": {"name": "Rainbow Childrens Medicare Ltd.", "industry": "Healthcare", "tier": "small"},
    "RKFORGE": {"name": "Ramkrishna Forgings Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "REDINGTON": {"name": "Redington Ltd.", "industry": "Services", "tier": "small"},
    "RPOWER": {"name": "Reliance Power Ltd.", "industry": "Power", "tier": "small"},
    "SBFC": {"name": "SBFC Finance Ltd.", "industry": "Financial Services", "tier": "small"},
    "SAGILITY": {"name": "Sagility Ltd.", "industry": "Information Technology", "tier": "small"},
    "SAILIFE": {"name": "Sai Life Sciences Ltd.", "industry": "Healthcare", "tier": "small"},
    "SAMMAANCAP": {"name": "Sammaan Capital Ltd.", "industry": "Financial Services", "tier": "small"},
    "SAPPHIRE": {"name": "Sapphire Foods India Ltd.", "industry": "Consumer Services", "tier": "small"},
    "SARDAEN": {"name": "Sarda Energy and Minerals Ltd.", "industry": "Metals & Mining", "tier": "small"},
    "SAREGAMA": {"name": "Saregama India Ltd", "industry": "Media Entertainment & Publication", "tier": "small"},
    "SCHNEIDER": {"name": "Schneider Electric Infrastructure Ltd.", "industry": "Capital Goods", "tier": "small"},
    "SCI": {"name": "Shipping Corporation of India Ltd.", "industry": "Services", "tier": "small"},
    "SHYAMMETL": {"name": "Shyam Metalics and Energy Ltd.", "industry": "Capital Goods", "tier": "small"},
    "SIGNATURE": {"name": "Signatureglobal (India) Ltd.", "industry": "Realty", "tier": "small"},
    "SOBHA": {"name": "Sobha Ltd.", "industry": "Realty", "tier": "small"},
    "SONACOMS": {"name": "Sona BLW Precision Forgings Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "SONATSOFTW": {"name": "Sonata Software Ltd.", "industry": "Information Technology", "tier": "small"},
    "STARHEALTH": {"name": "Star Health and Allied Insurance Company Ltd.", "industry": "Financial Services", "tier": "small"},
    "SUMICHEM": {"name": "Sumitomo Chemical India Ltd.", "industry": "Chemicals", "tier": "small"},
    "SUNTV": {"name": "Sun TV Network Ltd.", "industry": "Media Entertainment & Publication", "tier": "small"},
    "SPLPETRO": {"name": "Supreme Petrochem Ltd.", "industry": "Chemicals", "tier": "small"},
    "SWANCORP": {"name": "Swan Corp Ltd.", "industry": "Chemicals", "tier": "small"},
    "SYNGENE": {"name": "Syngene International Ltd.", "industry": "Healthcare", "tier": "small"},
    "SYRMA": {"name": "Syrma SGS Technology Ltd.", "industry": "Capital Goods", "tier": "small"},
    "TBOTEK": {"name": "TBO Tek Ltd.", "industry": "Consumer Services", "tier": "small"},
    "TATACHEM": {"name": "Tata Chemicals Ltd.", "industry": "Chemicals", "tier": "small"},
    "TATATECH": {"name": "Tata Technologies Ltd.", "industry": "Information Technology", "tier": "small"},
    "TTML": {"name": "Tata Teleservices (Maharashtra) Ltd.", "industry": "Telecommunication", "tier": "small"},
    "TECHNOE": {"name": "Techno Electric & Engineering Company Ltd.", "industry": "Construction", "tier": "small"},
    "TEGA": {"name": "Tega Industries Ltd.", "industry": "Capital Goods", "tier": "small"},
    "TEJASNET": {"name": "Tejas Networks Ltd.", "industry": "Telecommunication", "tier": "small"},
    "TENNIND": {"name": "Tenneco Clean Air India Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "RAMCOCEM": {"name": "The Ramco Cements Ltd.", "industry": "Construction Materials", "tier": "small"},
    "TIMKEN": {"name": "Timken India Ltd.", "industry": "Capital Goods", "tier": "small"},
    "TITAGARH": {"name": "Titagarh Rail Systems Ltd.", "industry": "Capital Goods", "tier": "small"},
    "TARIL": {"name": "Transformers And Rectifiers (India) Ltd.", "industry": "Capital Goods", "tier": "small"},
    "TRAVELFOOD": {"name": "Travel Food Services Ltd.", "industry": "Consumer Services", "tier": "small"},
    "TRIDENT": {"name": "Trident Ltd.", "industry": "Textiles", "tier": "small"},
    "TRITURBINE": {"name": "Triveni Turbine Ltd.", "industry": "Capital Goods", "tier": "small"},
    "UCOBANK": {"name": "UCO Bank", "industry": "Financial Services", "tier": "small"},
    "UTIAMC": {"name": "UTI Asset Management Company Ltd.", "industry": "Financial Services", "tier": "small"},
    "URBANCO": {"name": "Urban Company Ltd.", "industry": "Consumer Services", "tier": "small"},
    "USHAMART": {"name": "Usha Martin Ltd.", "industry": "Capital Goods", "tier": "small"},
    "VTL": {"name": "Vardhman Textiles Ltd.", "industry": "Textiles", "tier": "small"},
    "VIJAYA": {"name": "Vijaya Diagnostic Centre Ltd.", "industry": "Healthcare", "tier": "small"},
    "WELCORP": {"name": "Welspun Corp Ltd.", "industry": "Capital Goods", "tier": "small"},
    "WELSPUNLIV": {"name": "Welspun Living Ltd.", "industry": "Textiles", "tier": "small"},
    "WHIRLPOOL": {"name": "Whirlpool of India Ltd.", "industry": "Consumer Durables", "tier": "small"},
    "WOCKPHARMA": {"name": "Wockhardt Ltd.", "industry": "Healthcare", "tier": "small"},
    "ZFCVINDIA": {"name": "ZF Commercial Vehicle Control Systems India Ltd.", "industry": "Automobile and Auto Components", "tier": "small"},
    "ZEEL": {"name": "Zee Entertainment Enterprises Ltd.", "industry": "Media Entertainment & Publication", "tier": "small"},
    "ZENTEC": {"name": "Zen Technologies Ltd.", "industry": "Capital Goods", "tier": "small"},
    "ZENSARTECH": {"name": "Zensar Technolgies Ltd.", "industry": "Information Technology", "tier": "small"},
    "ZYDUSWELL": {"name": "Zydus Wellness Ltd.", "industry": "Fast Moving Consumer Goods", "tier": "small"},
    "ECLERX": {"name": "eClerx Services Ltd.", "industry": "Services", "tier": "small"},
}

# Bare symbols with at least one live NSE equity-derivative (futures or options) contract
# on Upstox's instrument master - i.e. the actual current F&O-eligible universe, not a guess.
FNO_ENABLED_SYMBOLS = [
    "360ONE", "ABB", "ABCAPITAL", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER",
    "ALKEM", "AMBER", "AMBUJACEM", "ANGELONE", "APLAPOLLO", "APOLLOHOSP", "ASHOKLEY", "ASIANPAINT",
    "ASTRAL", "AUBANK", "AUROPHARMA", "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BAJAJHLDNG", "BAJFINANCE",
    "BANDHANBNK", "BANKBARODA", "BANKINDIA", "BDL", "BEL", "BHARATFORG", "BHARTIARTL", "BHEL",
    "BIOCON", "BLUESTARCO", "BOSCHLTD", "BPCL", "BRITANNIA", "BSE", "CAMS", "CANBK",
    "CDSL", "CGPOWER", "CHOLAFIN", "CIPLA", "COALINDIA", "COCHINSHIP", "COFORGE", "COLPAL",
    "CONCOR", "CROMPTON", "CUMMINSIND", "DABUR", "DALBHARAT", "DELHIVERY", "DIVISLAB", "DIXON",
    "DLF", "DMART", "DRREDDY", "EICHERMOT", "ETERNAL", "EXIDEIND", "FEDERALBNK", "FORCEMOT",
    "FORTIS", "GAIL", "GLENMARK", "GMRAIRPORT", "GODFRYPHLP", "GODREJCP", "GODREJPROP", "GRASIM",
    "GVT&D", "HAL", "HAVELLS", "HCLTECH", "HDFCAMC", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO",
    "HINDALCO", "HINDPETRO", "HINDUNILVR", "HINDZINC", "HYUNDAI", "ICICIBANK", "ICICIGI", "ICICIPRULI",
    "IDEA", "IDFCFIRSTB", "IEX", "INDHOTEL", "INDIANB", "INDIGO", "INDUSINDBK", "INDUSTOWER",
    "INFY", "INOXWIND", "IOC", "IREDA", "IRFC", "ITC", "JINDALSTEL", "JIOFIN",
    "JSWENERGY", "JSWSTEEL", "JUBLFOOD", "KALYANKJIL", "KAYNES", "KEI", "KFINTECH", "KOTAKBANK",
    "KPITTECH", "LAURUSLABS", "LICHSGFIN", "LICI", "LODHA", "LT", "LTF", "LTM",
    "LUPIN", "M&M", "MANAPPURAM", "MANKIND", "MARICO", "MARUTI", "MAXHEALTH", "MAZDOCK",
    "MCX", "MFSL", "MOTHERSON", "MOTILALOFS", "MPHASIS", "MUTHOOTFIN", "NAM-INDIA", "NATIONALUM",
    "NAUKRI", "NBCC", "NESTLEIND", "NHPC", "NMDC", "NTPC", "NUVAMA", "NYKAA",
    "OBEROIRLTY", "OFSS", "OIL", "ONGC", "PAGEIND", "PATANJALI", "PAYTM", "PERSISTENT",
    "PETRONET", "PFC", "PGEL", "PHOENIXLTD", "PIDILITIND", "PIIND", "PNB", "PNBHOUSING",
    "POLICYBZR", "POLYCAB", "POWERGRID", "POWERINDIA", "PREMIERENE", "PRESTIGE", "RADICO", "RBLBANK",
    "RECLTD", "RELIANCE", "RVNL", "SAIL", "SBICARD", "SBILIFE", "SBIN", "SHREECEM",
    "SHRIRAMFIN", "SIEMENS", "SOLARINDS", "SONACOMS", "SRF", "SUNPHARMA", "SUPREMEIND", "SUZLON",
    "SWIGGY", "TATACONSUM", "TATAELXSI", "TATAPOWER", "TATASTEEL", "TCS", "TECHM", "TIINDIA",
    "TITAN", "TMPV", "TORNTPHARM", "TRENT", "TVSMOTOR", "ULTRACEMCO", "UNIONBANK", "UNITDSPR",
    "UNOMINDA", "UPL", "VBL", "VEDL", "VMM", "VOLTAS", "WAAREEENER", "WIPRO",
    "YESBANK", "ZYDUSLIFE",
]

TIER_LABELS = {"large": "Large Cap (Nifty 100)", "mid": "Mid Cap (Nifty Midcap 150)", "small": "Small Cap (Nifty Smallcap 250)"}

BY_TIER = {tier: [] for tier in TIER_LABELS}
for _sym, _info in NSE_UNIVERSE.items():
    BY_TIER[_info["tier"]].append(_sym)

BY_SECTOR = {}
for _sym, _info in NSE_UNIVERSE.items():
    BY_SECTOR.setdefault(_info["industry"], []).append(_sym)

ALL_SYMBOLS = list(NSE_UNIVERSE.keys())

